### PR TITLE
Update Project structure and dependencies

### PR DESCRIPTION
**Pull request by gswifort**
Related: #145, #150, #152

I have adapted some of the work described [here](https://github.com/CEXT-Dan/PyRx/discussions/86#discussioncomment-9822656) to the current repository content.

1. Updated ``.gitignore`` with standard entries for Windows, Python, and Visual Studio Code
1. I have tidied up (moved) modules (bindings, activex) - You need to move the generation of ``_rx`` and ``pyi`` files for them to ``bindings`` directory,
1. Rewrote most of ``setup.py`` to ``pyproject.toml`` ([PEP 621](https://peps.python.org/pep-0621/))
1. version in ``pyproject.toml`` is automatically read from ``pyrx/__init__.py``
1. Added ``build`` to dependencies - as described [here](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/), ``python setup.py sdist`` and ``python setup.py bdist_wheel`` should no longer be used. Therefore, you should also update ``.github\workflows\publish.yml``, but I'll leave that to your decision. 

Entries in ``pyproject.toml`` will cause ``pip install cad-pyx`` to install only ``wxpython``. ``debugpy`` is needed "only" for debugging and is not required if someone wants to use ready-made solutions.
Additionally, you can:

- ``pip install cad-pyx[activex]`` - will additionally install ``pywin32``,
- ``pip install cad-pyx[dev]`` will additionally install ``debugpy``, ``pytest`` and other development tools,
- ``pip install cad-pyx[full]`` will install everything above.

There are still a few things that need to be added, but I'm sharing this PR to start the discussion:

- [ ] Tests (I plan to use ``pytest``, so I've already added it to the dependencies),
- [ ] update README with the above information,
- [ ] merge README and READMEINSTALL - in my opinion, this shouldn't be split into two documents.

### CODE REVIEW

**Comment by CEXT-Dan** [comment]
Thank you! I think this should have been discussed first.

I only want to have PIP install.. easy, simple, installs everything 
This needs to install everything, ActiveX, C++ wrappers, and the tools needed to debug.
There are somethings that are easier to do in ActiveX, such as zoom and save.  

People want to debug, see http://www.theswamp.org/index.php?topic=59915.msg623022#msg623022
Debugging is part of AutoLISP in VS Code, it needs to be included here

**Comment by CEXT-Dan** [comment]
there needs to be a global version number, there's too many places for it to be changed 
>__version__ = "2.1.7"

**Comment by CEXT-Dan** [comment]
> there needs to be a global version number, there's too many places for it to be changed
> 
> > **version** = "2.1.7"

I see there's only one.

**Comment by CEXT-Dan** [comment]
>pip install cad-pyx[full]
this is default right?

**Comment by CEXT-Dan** [comment]
I had to revert git ignore, it was no longer filtering the C++ build objects

**Comment by CEXT-Dan** [comment]
I had to move everything back to pyrx. 
my unit tests quit working, maybe you can check if __init__.py is okay

**Comment by gswifort** [comment]
> > pip install cad-pyx[full]
> 
> this is default right?

No, only ``wxpython`` is default.
As you suggested I will add ``pywin32`` and ``debugpy`` to the default. ``pytest``, ``build`` and other development tools will remain optional.

**Comment by gswifort** [comment]
> I had to revert git ignore, it was no longer filtering the C++ build objects

that's strange, what files are you talking about? Are they supposed to be ignored but aren't, or is it the other way around?

**Comment by gswifort** [comment]
> I had to move everything back to pyrx. my unit tests quit working, maybe you can check if **init**.py is okay

I don't think you should merge this before testing if the changes are correct. For the future, I suggest downloading the PR to a temporary branch and committing if you think it's ok.

**Comment by gswifort** [comment]
> I had to move everything back to pyrx. my unit tests quit working, maybe you can check if **init**.py is okay

Tests work for me. I loaded the file ``unitTests\UnitTestRunner.py`` and called ``RUNTESTS``, the file ``unitTests\testResults\tout_ZRX25_2024_12_30 21_07_48_555989_2024_12_30 21_07_48_555988.txt`` was generated (282 lines), all tests passed.

**Comment by gswifort** [comment]
> > I had to revert git ignore, it was no longer filtering the C++ build objects
> 
> that's strange, what files are you talking about? Are they supposed to be ignored but aren't, or is it the other way around?

Ok, I accidentally deleted these lines:

```raw
/PyRxLoader/RxLoaderV25.0
/PyRxCore/PyRxV25.0
/PyRxLoader/RxLoaderG25.0
/PyRxCore/PyRxG25.0
/PySamples/dwg/*.bak
/unitTests/testmedia/*.ds$
/unitTests/testmedia/*.log
/unitTests/testmedia/*.bak
```

I think you added them after I made the changes in gitignore and didn't notice it when merging.

**Comment by CEXT-Dan** [comment]
> Tests work for me.

I do my work with the modules uninstalled, I think that’s the reason the tests failed, it could not find the sub paths 
There’s no way you could have known this, since we’re working in different environments

I think we have different views on who the target audience is, I see this project more as a replacement for AutoLISP. If you look at the AutoLISP community, they tend to write and share their routines. It’s a real hackathon where script writers use R13 style lisp and ActiveX (VLA- VLAX-), they copy/paste and run.  

I expect the same for those who are sharing Python code, and I don’t want people to have to go back and install ActiveX, just because someone’s code references it. Additionally, I expect people will want to debug routines. 

There may be a case where a developer wants to distribute a subset of the package, i.e. sans ActiveX, debug. In this case, it’s the developer’s responsibility to do this, i.e. pip install cad-pyrx[lean]. 
The default should be cad-pyrx[full].

**Comment by CEXT-Dan** [comment]
BTW, I do appreciate your input, a lot, your Python skills are far superior than mine! Took me hours to get my first post to PyPi working lol

**Comment by gswifort** [comment]
Optional dependencies (`pip install cad-pyrx[lean]`) must be a superset of defaults (`pip install cad-pyrx)`. But I understand your reasoning, I've already fixed that in https://github.com/gswifort/PyRx/commit/eb7e32aeae13129483e09a56b90391e4614e9c31, will submit it in the next PR once we agree on the rest.

**Comment by gswifort** [comment]
> I think we have different views on who the target audience is, I see this project more as a replacement for AutoLISP. If you look at the AutoLISP community, they tend to write and share their routines. It’s a real hackathon where script writers use R13 style lisp and ActiveX (VLA- VLAX-), they copy/paste and run.

Yes, I see potential in this project to build many (big and small) extensions on it. I hope we can combine these two views :)

And besides, I also see it as a replacement for LISP. I implemented REPL for a reason :)

**Comment by CEXT-Dan** [comment]
I added this line to project.toml, I did not see the ARX modules without it, hope its right

```
[tool.setuptools.package-data]
pyrx = ["*.arx", "*.brx", "*.grx", "*.zrx"]
``

**Comment by CEXT-Dan** [comment]
I made a file GitResources/long_description.md for PyPi 's page as README.md does not render correctly 
it worked with setup.py but not with project.toml

**Comment by CEXT-Dan** [comment]
The pages probably need to be cleaned up, I noticed that PyPi does non pick up the images in README.md, so it looks a little weird, hence the long_description 
Also, I didn’t quite understand how I should edit .github\workflows\publish.yml. 
I noticed the wheel name is any_none, I don’t how, but I assume that should be win_x64?

**Comment by gswifort** [comment]
> I added this line to project.toml, I did not see the ARX modules without it, hope its right
> 
> ```
> [tool.setuptools.package-data]
> pyrx = ["*.arx", "*.brx", "*.grx", "*.zrx"]
> ``
> ```

This was done in ``MANIFEST.in``, but the bindings were moved to the ``pyrx`` directory.

```cfg
# MANIFEST.in
include pyrx/bindings/*.arx
include pyrx/bindings/*.brx
include pyrx/bindings/*.grx
include pyrx/bindings/*.zrx
```

**Comment by gswifort** [comment]
> I made a file GitResources/long_description.md for PyPi 's page as README.md does not render correctly it worked with setup.py but not with project.toml

``long_description.md`` is the only one left in ``setup.py``, I think the problem is that this file was not included in ``MANIFEST.in``. It would work with ``python setup.py sdist bdist_wheel``, but it won't work (without an entry in ``MANIFEST.in``) with ``python -m build`` because ``build`` by default creates an environment separate from the repository and builds .whl from it (among other things, to check if the source distribution is complete - without ``long_description.md`` it wouldn't be).

**Comment by CEXT-Dan** [comment]
okay, I goofed that up then, I renamed the file to PYPI_REAMDME and removed setup.py

**Comment by gswifort** [comment]
> I do my work with the modules uninstalled, I think that’s the reason the tests failed, it could not find the sub paths
There’s no way you could have known this, since we’re working in different environments

I still don't understand why this doesn't work.
I run zwcad from the global environment, load RxLoader, pyload ``unitTests\UnitTestRunner.py`` and ``RUNTESTS``. All imports are absolute (e.g. ``import PyRx`` or ``import testcfg``), so if the main module is loaded (e.g. PyRxZ25.0.zrx), it should work.

**Comment by CEXT-Dan** [comment]
when I write in C++, I run everything out of the repo, still using the .INI to the stub path. 
I think having more than one stub path messes me up. It’s way easier for me to switch with just one path
also, the main module loads itself in sys.path, it did not see the ActiveX folder

everything is fine now, I can switch from debug to release easily

**Comment by CEXT-Dan** [comment]
No, it should stay a monolith directory.

**Comment by CEXT-Dan** [comment]
Just to add, there can be other directories for add-on tools, and what not, stuff that does not affect my development.

-pyrx
---core (includes everything that's in pyrx now)
---something else 

For me it’s easy to switch from local debug, release and installed, if everything referenced in pyrx_imp.py and pyrx_impx.py is in the same directory.  There could be some higher up import module that I don’t need to worry about. 
I can set my stub path to where ever pyrx_imp.py and pyrx_impx.py are, if that makes sense

**Comment by gswifort** [comment]
Yes, I think that will be ok.

Although I guess you could simply replace in the tests (and samples):
- ``from pyrx_imp import Rx, Ap, ...`` → ``from pyrx import Rx, Ap, ...``
- ``from pyrx_impx import Ax`` → ``from pyrx.activex import Ax``

I don't insist, the solution with pyrx_imp also works, but it just might be a bit confusing for new developers in the future.

**Comment by CEXT-Dan** [comment]
> Yes, I think that will be ok.
> 
> Although I guess you could simply replace in the tests (and samples):
> 
>     * `from pyrx_imp import Rx, Ap, ...` → `from pyrx import Rx, Ap, ...`
> 
>     * `from pyrx_impx import Ax` → `from pyrx.activex import Ax`
> 
> 
> I don't insist, the solution with pyrx_imp also works, but it just might be a bit confusing for new developers in the future.

 Yes, we can do this

**Comment by CEXT-Dan** [comment]
Thinking, if we change this, it should be 
From pyrx import Ax at the same level as Ap

**Comment by CEXT-Dan** [comment]
> > I added this line to project.toml, I did not see the ARX modules without it, hope its right
> > ```
> > [tool.setuptools.package-data]
> > pyrx = ["*.arx", "*.brx", "*.grx", "*.zrx"]
> > ``
> > ```
> 
> This was done in `MANIFEST.in`, but the bindings were moved to the `pyrx` directory.
> 
> ```haproxy-config
> # MANIFEST.in
> include pyrx/bindings/*.arx
> include pyrx/bindings/*.brx
> include pyrx/bindings/*.grx
> include pyrx/bindings/*.zrx
> ```

MANIFEST can be removed ?

**Pull request merged**
