### PR TITLE
Add PyBrxCvDbLabelStyle

### PR DESCRIPTION
**Pull request by schoeller**
Does not compile, please check thoroughly.

### CODE REVIEW

**Comment by schoeller** [comment]
1. PyBrxCv.cpp does not compile
```
#if !defined(_BRXTARGET240)
    enum_<BrxCvDbLabelStyleLine::LengthType>("LengthType")
        .value("eLengthTypeFixed", BrxCvDbLabelStyleLine::LengthType::eLengthTypeFixed)
        .value("eLengthTypePercentage", BrxCvDbLabelStyleLine::LengthType::eLengthTypePercentage)
        .export_values()
        ;
#endif 
```

2. Trouble handling Ptr in class definition PyBrxCvDbLabelStyle
```
BrxCvDbLabelStyleComponentPtrArray components() const;
BrxCvDbLabelStyleComponentPtr      componentAt(Adesk::UInt32 index) const;
BrxCvDbLabelStyleComponentPtr      component(const AcString& name) const;
```

3. Questionable method translations for PyBrxCvDbLabelStyle
`{ "val: LeaderAttachment" }`

4. Questionable argument translation for PyBrxCvDbLabelStyle
```
void PyBrxCvDbLabelStyle::expressionAt(Adesk::UInt32 index, AcString& name, AcString& expr, BrxCvDataType& type) const
{
    PyThrowBadEs(impObj()->expressionAt(index, name, type)); //SSC
}

void PyBrxCvDbLabelStyle::setExpressionAt(Adesk::UInt32 index, const AcString& name, const AcString& expr, BrxCvDataType type)
{
    PyThrowBadEs(impObj()->expressionAt(index, name, expr, type)); //SSC
```

Hope you can fix it.

**Comment by schoeller** [comment]
Learning from mistakes:

3. I should have written as per [fix](https://github.com/CEXT-Dan/PyRx/commit/92ebac6e92914223783ef613953f30f18c0e8ec0#diff-e3f8ae97afa8b872934e9d3af3cf2150fbf8a5cb4c689fd1e29c0f9e26a95b0fR607) 
{ "val: PyBrxCv.LeaderAttachment" }

5. Several mistaken in base classes (flippancy)

6. Syntax error (flippancy)

7. Modify inline statement

**Comment by CEXT-Dan** [comment]
>Learning from mistakes:

You’re doing awesome! bugs and errors are part of the process :)
there’s a couple of functions that will need to be tested, I marked with TODO:
ideally, there should be a high amount of tests / samples

**Comment by schoeller** [comment]
I may be able to provide a test sample and may study from your coding. Will otherwise try to follow as advised.



[TestLabel.zip](https://github.com/user-attachments/files/17739417/TestLabel.zip)

**Pull request merged**
